name: Teste Automático

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:  # A indentação deve ser corrigida aqui
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 

      - name: Instalar dependências
        run: npm install
    
      - name: Rodar testes
        run: npm test
